### ISSUE TITLE
Change redirectUrl when payment was completed and 'back to the game' button is clicked

### ISSUE THREAD

**Issue by hamburml** [xsolla/paystation-embed#10]
Hello,

I am adding Xsolla as payment service to our game. Currently on our browser-game we use the paystation widget v1.0.7 and the sandbox-mode is set to true in the options. The created app uses our dev-server which is the backend for the browser-game. The browser-game has socket-connections to the backend and the backend informs the frontend via socket that a payment was completed.

When the payment was completed and the 'back to the game' button is clicked, the whole site is reloaded. I don't want to reload the whole page, I just want to close the paystation widget. How can I do this? I don't find a setting.

I could add a 'status-done' event and close the paystation widget via javascript but I think that's not the best way... (this would hide the back to the game button and hence it's not possible to click it, so there won't be a redirection) 

Any advice?

Thank you!

**Comment by hamburml** [comment]
There is a working solution, thanks to the fast and great xsolla support.
A project can have a Return URL. The Return URL can have additional options (even when it's empty). The Redirect Conditions and Status for manuel redirection can be set to 'Never' and the redirect-button is gone :) Thanks again!

**Comment by elios264** [comment]
hey @hamburml is there any doc for these conditions? can I see your redirec_url if possible?
